const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require(process.env.SIT_TEST_MODULES?path.join(process.env.SIT_TEST_MODULES,'jsdom'):'jsdom');
const root=path.join(__dirname,'..'),script=fs.readFileSync(path.join(root,'wordpress/themes/sit-technology/assets/discovery.js'),'utf8');
function open(slug='',hash=''){
 const html=fs.readFileSync(path.join(root,'dist',slug,'index.html'),'utf8');
 const dom=new JSDOM(html,{url:'https://sit.example/'+slug+(slug?'/':'')+hash,runScripts:'outside-only'});
 const w=dom.window;w.HTMLElement.prototype.scrollIntoView=function(){};w.matchMedia=()=>({addEventListener(){}});
 w.eval(fs.readFileSync(path.join(root,'wordpress/themes/sit-technology/assets/site.js'),'utf8'));w.eval(script);return dom;
}
let dom=open(),w=dom.window,d=w.document;
d.querySelector('.expertise-toggle').click();assert.equal(d.querySelector('#expertise-menu').hidden,false);d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));assert.equal(d.querySelector('#expertise-menu').hidden,true);assert.equal(d.activeElement,d.querySelector('.expertise-toggle'));
let tabs=[...d.querySelectorAll('.ambition-tabs [role=tab]')];tabs[0].dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,cancelable:true}));assert.equal(tabs[1].getAttribute('aria-selected'),'true');assert.equal(d.querySelector('#ambition-panel-0').hidden,true);assert.equal(d.querySelector('#ambition-panel-1').hidden,false);
d.querySelector('.search-open').click();assert.equal(d.querySelector('#site-search').hasAttribute('open'),true);let input=d.querySelector('#site-search-input');input.value='cloud';input.dispatchEvent(new w.Event('input'));assert.match(d.querySelector('#search-results').textContent,/Cloud & DevOps/);assert.equal([...d.querySelectorAll('.search-result')].every(a=>a.href.startsWith('https://sit.example/')),true);
input.value='<img src=x onerror=alert(1)>';input.dispatchEvent(new w.Event('input'));assert.equal(d.querySelector('#search-results img'),null);assert.match(d.querySelector('#search-results').textContent,/different phrase/);
d.querySelector('[data-search-term=AI]').click();assert.match(d.querySelector('#search-results').textContent,/AI project planner/);d.querySelector('.search-close').click();assert.equal(d.querySelector('#site-search').hasAttribute('open'),false);assert.equal(d.activeElement,d.querySelector('.search-open'));dom.window.close();
dom=open('services');w=dom.window;d=w.document;const visible=()=>[...d.querySelectorAll('.finder-card')].filter(el=>!el.hidden);assert.equal(visible().length,9);d.querySelector('[data-filter=ai-data]').click();assert.equal(visible().length,2);input=d.querySelector('#service-search');input.value='analytics';input.dispatchEvent(new w.Event('input'));assert.equal(visible().length,1);input.value='no-match-zebra';input.dispatchEvent(new w.Event('input'));assert.equal(visible().length,0);assert.equal(d.querySelector('.finder-empty').hidden,false);d.querySelector('[data-reset-finder]').click();assert.equal(visible().length,9);dom.window.close();
dom=open('industries','#2');w=dom.window;d=w.document;assert.equal(d.querySelector('#sector-tab-2').getAttribute('aria-selected'),'true');assert.equal(d.querySelector('#sector-panel-2').hidden,false);d.querySelector('#sector-tab-6').click();assert.equal(w.location.hash,'#6');assert.equal(d.querySelector('#sector-panel-6').hidden,false);assert.equal([...d.querySelectorAll('.industry-panels section')].filter(el=>!el.hidden).length,1);dom.window.close();
for(const [answer,title] of [['0','focused discovery'],['1','useful pilot'],['2','controlled delivery']]){
 dom=open('ai-readiness');w=dom.window;d=w.document;const form=d.querySelector('#ai-planner');form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(d.querySelector('#ai-result').hidden,true,'Incomplete questionnaire must not produce a result');form.querySelectorAll('select').forEach(el=>el.value=answer);form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(d.querySelector('#ai-result').hidden,false);assert.match(d.querySelector('#ai-result-title').textContent,new RegExp(title));assert.ok(d.querySelectorAll('#ai-result-actions li').length>=3);assert.equal(w.localStorage.length,0);d.querySelector('#ai-reset').click();assert.equal(form.hidden,false);assert.equal(form.querySelector('select').value,answer);dom.window.close();
}
dom=open('capabilities');let printed=false;dom.window.print=()=>{printed=true;};dom.window.document.querySelector('[data-print]').click();assert.equal(printed,true);dom.window.close();
console.log('PASS: expertise disclosure, keyboard tabs, safe local search, combined service filters, sector deep links, all three AI planning paths, no planner storage and print action.');
