"""The About page: company context and useful next steps, without invented proof."""
from redesign import a, url, asset


def build_about_page():
    roles = [
        ('Client leadership', 'Close to the decisions that matter.',
         'UK client leadership connects the business challenge to a practical delivery plan. We agree who owns priorities, who approves decisions and how progress will be reviewed.',
         ['A named point of contact for the engagement', 'Clear scope, responsibilities and review points'],
         'engagement-models', 'Compare ways to work'),
        ('Engineering', 'Technical talent. Shared ownership.',
         'Developers in Liberia and across Africa bring engineering capability to the work. Team composition, relevant skills and availability are agreed around your project—not a generic list of technologies.',
         ['Skills matched to the proposed scope', 'Working increments, review and documentation'],
         'technologies', 'Explore our technology toolkit'),
        ('One connected team', 'Distance should not create uncertainty.',
         'Before work begins, we agree shared working hours, communication channels, access and escalation. Your team stays involved through demonstrations, decisions and a clear handover.',
         ['An agreed collaboration and review rhythm', 'Knowledge transfer and operating ownership'],
         'how-we-work', 'Explore our delivery model'),
    ]
    tabs = ''.join(f'<button type="button" role="tab" id="about-role-{i}" aria-controls="about-role-panel-{i}" aria-selected="{str(i == 0).lower()}" tabindex="{0 if i == 0 else -1}"><span aria-hidden="true">0{i+1}</span>{row[0]}</button>' for i, row in enumerate(roles))
    panels = ''.join(f'<section role="tabpanel" id="about-role-panel-{i}" aria-labelledby="about-role-{i}" tabindex="0"{" hidden" if i else ""}><h3>{row[1]}</h3><p>{row[2]}</p><ul>'+''.join(f'<li>{item}</li>' for item in row[3])+f'</ul>{a(row[4],row[5])}</section>' for i,row in enumerate(roles))
    principles = [
        ('Be clear', 'Make the important things visible.', 'Agree scope, explain trade-offs and raise uncertainty early. Progress should be understandable to the people making decisions.'),
        ('Care about the craft', 'Build for the people who will use it.', 'Bring useful design, code review, testing and documentation into the work—not just the final handover.'),
        ('Keep AI accountable', 'Accelerate the work. Keep human judgement.', 'Use AI where it serves a clear purpose, with appropriate information access, evaluation and engineers responsible for the result.'),
        ('Grow together', 'Leave more capability behind.', 'Share knowledge, support engineering development and help your team understand and own what we build together.'),
    ]
    values = ''.join(f'<article><span class="about-index" aria-hidden="true">0{i+1}</span><div><p class="eyebrow">{title}</p><h3>{heading}</h3><p>{copy}</p></div></article>' for i,(title,heading,copy) in enumerate(principles))
    questions = [
        ('Where is SIT Consultancy based?', 'SIT Consultancy is headquartered in the United Kingdom, with developers in Africa, including Liberia. The people involved, working arrangements and responsibilities are confirmed for each engagement.'),
        ('How can we work with SIT?', 'Start with discovery and advisory, a defined software or technology project, or a dedicated engineering team. We clarify scope, relevant skills, availability and commercial terms before an engagement begins.'),
        ('Can you work alongside our existing team?', 'Yes. We first agree how your team and SIT will share priorities, technical decisions, access, working hours and delivery reviews. The model can include your existing suppliers and internal engineering team.'),
        ('Which technologies do you work with?', 'Our service areas span software, AI, data, cloud and enterprise integration. We discuss the specific languages, frameworks and platforms your work requires, then confirm suitable capability in the proposed team.'),
        ('How do you approach confidentiality and AI?', 'Confidentiality, information access and any use of AI tools should be agreed before project material is shared. Discuss an NDA or procurement requirements in your initial enquiry; do not submit confidential files, credentials or sensitive personal information through the public form.'),
        ('Can I join the engineering team?', 'Our Careers page is the place for published opportunities and application information. Roles depend on project needs and required capabilities; the website does not promise an available vacancy or immediate placement.'),
    ]
    faqs = ''.join(f'<details><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>' for question,answer in questions)
    body = f'''<div class="about-page">
<section class="about-hero"><div class="wrap about-hero-grid"><div><p class="eyebrow">ABOUT SIT CONSULTANCY</p><h1>Different perspectives.<br><em>One shared ambition.</em></h1><p class="lead">UK leadership. African engineering. Technology built around the people it needs to serve.</p><p>We bring consulting, software, data and AI together to help organisations turn a meaningful challenge into a practical way forward.</p><div class="actions">{a('start-a-project','Meet your next technology partner','button')}{a('capabilities','View company capabilities')}</div></div><figure class="about-hero-art"><img src="{asset('bridge-apple-gold.png')}" width="1536" height="1024" alt="Orange and yellow glass bridge, a symbol of connected delivery" fetchpriority="high"><figcaption><span>SIT / CONNECTED PERSPECTIVES</span><strong>A bridge between<br>talent and opportunity.</strong></figcaption></figure></div></section>
<nav class="about-jump wrap" aria-label="On this About page"><span>Get to know SIT</span><a href="#about-story">Our story</a><a href="#about-delivery">Connected delivery</a><a href="#about-principles">Our principles</a><a href="#about-questions">Your questions</a></nav>
<section class="wrap about-section about-story-grid" id="about-story"><div><p class="eyebrow">WHY WE’RE BUILDING SIT</p><h2>Good technology starts<br>with understanding people.</h2></div><div class="about-story-copy"><p class="lead">Ambitious organisations need more than technical capacity. They need people who understand the challenge, ask useful questions and take responsibility for the work.</p><p>Headquartered in the United Kingdom, with developers in Africa including Liberia, SIT Consultancy brings people together around meaningful work. Our focus is practical: understand your challenge, assemble the relevant expertise and shape an approach your organisation can work with.</p><p>We believe the best partnerships create lasting capability. That means sharing knowledge, developing engineers and helping your team own what we build together.</p><dl class="about-at-glance"><div><dt>Headquarters</dt><dd>United Kingdom</dd></div><div><dt>Engineering talent</dt><dd>Liberia &amp; across Africa</dd></div><div><dt>Our focus</dt><dd>Software, AI, data &amp; cloud</dd></div></dl></div></section>
<section class="about-connected" id="about-delivery"><div class="wrap about-section"><div class="about-section-heading"><div><p class="eyebrow">THE PEOPLE BEHIND THE WORK</p><h2>Different locations.<br><em>One connected team.</em></h2></div><p>Business understanding and engineering craft belong in the same conversation. Here’s how we bring them together.</p></div><div class="about-delivery-explorer" data-tabs><div class="about-role-tabs" role="tablist" aria-label="Explore our delivery responsibilities">{tabs}</div><div class="about-role-panels">{panels}</div></div><div class="about-connected-foot"><p>Responsibilities, shared hours and delivery terms are agreed for your engagement.</p>{a('delivery-assurance','How we build confidence')}</div></div></section>
<section class="wrap about-section" id="about-principles"><div class="about-section-heading"><div><p class="eyebrow">WHAT GUIDES US</p><h2>Principles you can see<br>in the way we work.</h2></div><p>Clear thinking, thoughtful engineering and a commitment to leave your team stronger.</p></div><div class="about-principles">{values}</div></section>
<section class="about-resources"><div class="wrap about-section"><div><p class="eyebrow">GET TO KNOW US BETTER</p><h2>Useful detail.<br>Before the first conversation.</h2></div><div class="about-resource-list"><a href="{url('capabilities')}"><span>FOR YOUR TEAM</span><h3>Company capabilities</h3><p>A concise overview you can read, print or save as a PDF.</p><span class="about-resource-arrow" aria-hidden="true">↗</span></a><a href="{url('sample-deliverables')}"><span>FOR YOUR PROJECT</span><h3>Sample delivery documents</h3><p>Explore five editable examples for planning, quality and handover.</p><span class="about-resource-arrow" aria-hidden="true">↗</span></a><a href="{url('careers')}"><span>FOR YOUR NEXT CHAPTER</span><h3>Engineering at SIT</h3><p>Our approach to careers and the place to find published opportunities.</p><span class="about-resource-arrow" aria-hidden="true">↗</span></a></div></div></section>
<section class="wrap about-section about-questions" id="about-questions"><div><p class="eyebrow">BEFORE WE MEET</p><h2>A little more<br>about working with us.</h2><p>Still have a question? Start with a short enquiry and tell us what you need to know.</p>{a('start-a-project?type=enquiry','Ask us a question')}</div><div class="about-faq">{faqs}</div></section>
<section class="about-closing"><div class="wrap"><p class="eyebrow">YOUR AMBITION. OUR SHARED NEXT STEP.</p><h2>Let’s find out what<br>we can build together.</h2><p>A clearer direction. A useful product. The right engineering capability.</p><div class="actions">{a('start-a-project','Discuss your project','button')}{a('engagement-models','Explore ways to work')}</div></div></section>
</div>'''
    return {'title':'About SIT Consultancy','description':'Meet SIT Consultancy: UK leadership, engineering talent in Liberia and across Africa, shared principles and a connected approach to software, AI, data and cloud.','html':body}
