"""Contact and Team pages. Office details require confirmation; roles are mockups."""
from html import escape
from redesign import a, url

OFFICES = [('uk','United Kingdom','UK leadership','Europe/London'),('liberia','Liberia','Regional enquiries','Africa/Monrovia'),('cote-divoire','Côte d’Ivoire','Regional enquiries','Africa/Abidjan')]
ROLES = [
 ('leadership','MD','Managing Director','Company direction and client accountability.',['Set business priorities and commercial direction','Own governance and senior client relationships'],'technology-strategy'),
 ('leadership','CP','Client Partner','Connect business needs to the right engagement.',['Understand client goals and procurement requirements','Shape proposals and maintain stakeholder relationships'],'technology-strategy'),
 ('leadership','CTO','Technology & Architecture Lead','Make technical choices coherent and reviewable.',['Guide architecture and engineering standards','Review technical trade-offs and delivery risks'],'software-engineering'),
 ('leadership','LR','Liberia Country Lead','Coordinate regional partnerships and delivery readiness.',['Develop regional relationships and local coordination','Support team onboarding and operating arrangements'],'dedicated-teams'),
 ('leadership','CI','Côte d’Ivoire Country Lead','Connect regional opportunities and delivery teams.',['Support local business relationships and coordination','Clarify language, client and operating requirements'],'dedicated-teams'),
 ('delivery','DL','Delivery Lead','Keep the work aligned with agreed outcomes.',['Coordinate plans, dependencies and review points','Make risks and decisions visible to stakeholders'],'managed-services'),
 ('delivery','PM','Product Manager / Business Analyst','Turn a business problem into a useful product brief.',['Research workflows and define requirements','Prioritise outcomes and acceptance criteria'],'software-engineering'),
 ('delivery','UX','Product Designer','Make complex services clear and usable.',['Design accessible user journeys and prototypes','Test design assumptions with intended users'],'software-engineering'),
 ('engineering','EL','Engineering Lead','Guide implementation and support the team.',['Lead technical delivery and code review','Develop engineers and maintain quality standards'],'software-engineering'),
 ('engineering','FS','Full-stack Engineer','Build dependable applications and integrations.',['Implement interfaces, APIs and data access','Test, document and review production changes'],'software-engineering'),
 ('engineering','ME','Mobile Engineer','Create useful mobile experiences.',['Build mobile application journeys and integrations','Consider accessibility, device limits and offline behaviour'],'software-engineering'),
 ('engineering','AI','AI / Machine Learning Engineer','Turn a bounded use case into evaluated AI.',['Build and evaluate models or AI-assisted workflows','Document limitations, safeguards and human review'],'ai-and-automation'),
 ('engineering','DS','Data Scientist','Make analytical questions measurable.',['Explore data quality and statistical assumptions','Evaluate models and communicate uncertainty'],'data-and-analytics'),
 ('engineering','DE','Data Engineer','Make information reliable and usable.',['Build and monitor pipelines and transformations','Maintain definitions, validation and data lineage'],'data-and-analytics'),
 ('engineering','CD','Cloud & DevOps Engineer','Make delivery and operations repeatable.',['Build infrastructure and deployment automation','Support monitoring, recovery and environment controls'],'cloud-and-devops'),
 ('engineering','QA','Quality Engineer','Build evidence for confident releases.',['Plan automated and exploratory testing','Track defects, accessibility checks and release evidence'],'quality-and-security'),
 ('operations','SP','Security & Privacy Lead','Bring appropriate controls into delivery.',['Coordinate secure engineering and access reviews','Support privacy, incident and supplier requirements'],'quality-and-security'),
 ('operations','TL','Talent & Learning Lead','Develop capability and match skills to work.',['Coordinate assessment, mentoring and learning plans','Support capability matching and team development'],'dedicated-teams'),
 ('operations','PO','People & Operations Lead','Make distributed work sustainable.',['Coordinate onboarding and people processes','Support equipment, connectivity and operating readiness'],'dedicated-teams'),
 ('operations','FC','Finance & Commercial Lead','Keep commercial commitments clear.',['Coordinate budgets, contracts and supplier administration','Support proposals, invoicing and delivery reporting'],'technology-strategy'),
]
GROUPS = [('all','All roles'),('leadership','Leadership'),('delivery','Product & delivery'),('engineering','Engineering'),('operations','People & operations')]

def build_company_pages(services):
    locations = '<div class="location-grid">'+''.join(f'<article class="location-card" id="office-{key}"><div class="location-card-head"><span class="location-code" aria-hidden="true">{code}</span><time data-office-clock="{tz}" aria-label="Current local time in {country}"></time></div><p class="eyebrow">{kind}</p><h3>{country}</h3><div class="location-details">{{{{office:{key}}}}}</div><a class="text-link" href="#contact-form" data-contact-region="{key}">Enquire about this location<span aria-hidden="true">↗</span></a></article>' for (key,country,kind,tz),code in zip(OFFICES,['UK','LR','CI']))+'</div><p class="company-note" id="location-copy-status" role="status"></p>'
    topics = [('general','General enquiry'),('project','Project question'),('procurement','Procurement / NDA'),('partnership','Partnership'),('careers','Careers question')]
    form = f'''<div class="contact-form-card"><p class="eyebrow">SEND AN ENQUIRY</p><h2 id="contact-form-title">What would you like to discuss?</h2><p class="contact-demo-note" data-contact-note>Design preview — use sample details. No message is sent or stored.</p><form method="post" id="contact-form" aria-labelledby="contact-form-title"><fieldset class="contact-fields"><legend class="screen-reader-text">Your contact details and enquiry</legend><div class="form-row"><div><label for="contact-name">Your name</label><input id="contact-name" name="name" autocomplete="name" maxlength="120" required></div><div><label for="contact-email">Email address</label><input id="contact-email" name="email" type="email" autocomplete="email" maxlength="190" required></div></div><label for="contact-company">Organisation or individual</label><input id="contact-company" name="company" autocomplete="organization" maxlength="190" placeholder="Your organisation, or Individual" required><div class="form-row"><div><label for="contact-topic">What is this about?</label><select id="contact-topic" name="contact_topic">{''.join(f'<option value="{k}">{v}</option>' for k,v in topics)}</select></div><div><label for="contact-region">Preferred location</label><select id="contact-region" name="contact_region"><option value="any">No preference</option>{''.join(f'<option value="{o[0]}">{o[1]}</option>' for o in OFFICES)}</select></div></div><label for="contact-message">Your message</label><textarea id="contact-message" name="brief" minlength="20" maxlength="3000" rows="5" aria-describedby="contact-message-hint" required></textarea><p id="contact-message-hint" class="field-hint">20–3,000 characters. Please leave out confidential files, credentials and sensitive personal information.</p><label class="consent"><input type="checkbox" name="consent" value="1" required><span>I agree that SIT can use these details to respond to my enquiry. <a href="{url('privacy')}">Read the privacy notice</a>.</span></label><div class="hp" aria-hidden="true"><label for="contact-website">Leave this field empty</label><input id="contact-website" name="website" tabindex="-1" autocomplete="off"></div></fieldset><button class="button" type="submit" id="contact-submit" disabled>Preview enquiry<span aria-hidden="true">↗</span></button><p id="contact-status" class="company-note" role="status"></p><button class="text-link" type="button" id="contact-edit" hidden>Edit details and start a new attempt</button></form><div id="contact-success" tabindex="-1" hidden><h3>Thank you for getting in touch.</h3><p id="contact-success-copy"></p><button type="button" class="button secondary" id="contact-reset">Start another enquiry</button></div><noscript><p>Please enable JavaScript to use the enquiry form. Published office contact details are also available below.</p></noscript></div>'''
    contact = f'''<div class="company-page"><section class="contact-intro"><div class="wrap contact-layout"><div class="contact-copy"><p class="eyebrow">CONTACT SIT CONSULTANCY</p><h1>Let’s start with<br><em>a good conversation.</em></h1><p class="lead">A question, a project or a new partnership. Tell us what you have in mind and where you’d like to connect.</p><div class="contact-paths">{a('start-a-project?type=software-project','Discuss a software project')}{a('start-a-project?type=consultation','Request a discovery conversation')}{a('start-a-project?type=dedicated-team','Explore a dedicated team')}{a('contact#locations','Find our locations')}</div><div class="contact-expect"><p class="eyebrow">WHAT HAPPENS NEXT</p><ol><li>We review your message and its context.</li><li>We identify the relevant next conversation.</li><li>We agree any scope, meeting or follow-up with you.</li></ol><p>Sending an enquiry does not book a meeting or commit you to an engagement.</p></div></div>{form}</div></section><section class="wrap company-section" id="locations"><div class="company-section-heading"><div><p class="eyebrow">CONNECT WITH SIT</p><h2>United Kingdom.<br>Liberia. Côte d’Ivoire.</h2></div><p>Choose the location most relevant to your enquiry. Confirm the published address and visiting arrangements before you travel.</p></div>[sit_component name="contact-locations"]</section><section class="company-help"><div class="wrap company-section"><div><p class="eyebrow">A LITTLE GUIDANCE</p><h2>Before you get in touch.</h2></div><div class="company-faq"><details><summary>Can I send an RFP or confidential document?<span aria-hidden="true">+</span></summary><p>Choose Procurement / NDA and describe the request without confidential material. We can first agree confidentiality and an appropriate document-transfer method. This form does not accept uploads.</p></details><details><summary>Can I visit an office?<span aria-hidden="true">+</span></summary><p>Check the location’s published address type and visiting information. A registered or correspondence address may not accept visitors. Contact us before planning a visit.</p></details><details><summary>Is this a job application?<span aria-hidden="true">+</span></summary><p>No. Use Careers question for a general question. Published roles and application instructions belong on our Careers page. The Team page currently shows an illustrative role structure.</p>{a('careers','Explore careers')}</details><details><summary>Will my enquiry subscribe me to marketing?<span aria-hidden="true">+</span></summary><p>No marketing subscription is created by this form. Your details are used to review and respond to your enquiry, as described in the privacy notice.</p></details></div></div></section></div>'''
    cards = ''.join(f'<article class="role-card" data-role-group="{group}" data-role-search="{escape((title+" "+desc+" "+" ".join(responsibilities)).lower(),quote=True)}"><div class="role-card-top"><span class="role-monogram" aria-hidden="true">{code}</span><span class="role-mock-label">Role mockup</span></div><p class="role-group">{dict(GROUPS)[group]}</p><h3>{title}</h3><p>{desc}</p><details><summary>Role responsibilities<span aria-hidden="true">+</span></summary><ul>'+''.join(f'<li>{item}</li>' for item in responsibilities)+f'</ul>{a("services/"+service,"Related expertise")}</details></article>' for group,code,title,desc,responsibilities,service in ROLES)
    team = f'''<div class="company-page team-page"><section class="team-intro"><div class="wrap"><p class="eyebrow">THE TEAM BEHIND THE APPROACH</p><h1>Different skills.<br><em>Shared responsibility.</em></h1><p class="lead">The roles that connect client understanding, thoughtful engineering and dependable delivery.</p><p class="team-disclosure"><strong>Team structure mockup.</strong> These are proposed role profiles, not named staff, confirmed headcount or advertised vacancies. Roles may be combined, phased or provided through partners as the business develops.</p></div></section><section class="wrap company-section team-directory" data-team-directory><div class="team-toolbar"><div><label for="team-search">Find a role or skill</label><input id="team-search" type="search" placeholder="Try architecture, AI or delivery" autocomplete="off"></div><p id="team-count" role="status">20 proposed roles</p></div><div class="filter-chips" aria-label="Filter team roles">{''.join(f'<button type="button" data-role-filter="{k}" aria-pressed="{str(k=="all").lower()}">{v}</button>' for k,v in GROUPS)}</div><div class="role-grid">{cards}</div><div class="team-empty" hidden><h2>No matching roles.</h2><p>Try another skill or clear the filters to see the proposed structure.</p><button type="button" class="button secondary" data-team-reset>Show all roles</button></div></section><section class="team-working"><div class="wrap company-section"><div><p class="eyebrow">HOW THE ROLES CONNECT</p><h2>A team shaped around<br>the work ahead.</h2></div><ol><li><h3>Understand &amp; shape</h3><p>Client, product and architecture roles clarify the problem, priorities and decisions.</p></li><li><h3>Build &amp; review</h3><p>Engineering, design and quality roles turn agreed scope into reviewable work.</p></li><li><h3>Operate &amp; improve</h3><p>Delivery, security, people and commercial roles support ownership and ongoing improvement.</p></li></ol></div></section><section class="wrap company-section team-next"><div><p class="eyebrow">BUILD WITH SIT</p><h2>Start with the capability<br>your project needs.</h2><p>We confirm the actual people, skills, availability and responsibilities in the proposed engagement.</p>{a('start-a-project?type=dedicated-team','Discuss your team needs','button')}</div><div><p class="eyebrow">GROW WITH SIT</p><h2>Bring your perspective.<br>Keep developing your craft.</h2><p>See our approach to careers and published opportunities. This role directory is a design mockup, not a recruitment listing.</p>{a('careers','Explore careers','button secondary')}</div></section></div>'''
    return {'contact':{'title':'Contact SIT Consultancy','description':'Contact SIT Consultancy about projects, partnerships and procurement, with UK, Liberia and Côte d’Ivoire location information.','html':contact},'team':{'title':'Our team roles','description':'Explore SIT Consultancy’s proposed team structure across leadership, product, delivery, engineering and operations. Clearly labelled role mockups.','html':team}}, locations
