"""Consultancy release: concrete offers, reviewable deliverables and clearer decisions."""
import json, re
from pathlib import Path
from html import escape
from redesign import a, url, asset, intro
from delivery_samples import SAMPLES
from about_page import build_about_page
from company_pages import build_company_pages

MODELS = [
 ('advisory','Discovery & advisory','Make a confident decision.','When the problem, priorities or technical direction need more clarity.','A discovery brief, options, risks and a practical roadmap.','SIT leads the agreed investigation; your sponsor owns the business decision.','A defined discovery scope, with fees agreed before work starts.','consultation','modernise'),
 ('project','Project delivery','Take an idea into use.','When you need a partner to design, build or modernise a product or platform.','Agreed increments, review evidence, release documentation and handover.','SIT leads the agreed delivery scope; your product owner reviews priorities and acceptance.','Milestones or time-based delivery, matched to scope and uncertainty.','software-project','build'),
 ('team','Dedicated engineering teams','Add capacity with purpose.','When you have a delivery direction and need relevant engineering skills.','An agreed team profile, onboarding plan and shared delivery rhythm.','Your team and SIT agree day-to-day leadership, responsibilities and escalation.','Team composition, availability and engagement terms confirmed after discovery.','dedicated-team','team'),
]
SERVICE_DETAIL = {
 'technology-strategy': ('Competing priorities. Disconnected systems. Unclear investment choices.', ['A current-state map of systems, users and constraints','Options with trade-offs and prioritised recommendations','A roadmap with dependencies, owners and decision points'], 'Access to business stakeholders, your system landscape and the decisions you need to make.', 'discovery-brief','consultation'),
 'software-engineering': ('A product to launch, a workflow to improve or an application to rebuild.', ['User journeys, prototypes and a prioritised product backlog','Reviewable software increments with agreed acceptance criteria','Source, release documentation and an ownership handover'], 'A product owner, access to intended users and a view of existing systems or prototypes.', 'architecture-decision','software-project'),
 'ai-and-automation': ('A promising AI idea needs a useful problem, reliable information and clear boundaries.', ['A use-case brief and data-access assessment','A bounded pilot with evaluation examples and human review','A deployment recommendation with operating risks and ownership'], 'A business owner, representative examples and permission to use the required information.', 'quality-review','software-project'),
 'data-and-analytics': ('Reports disagree, information is fragmented or decisions take too long.', ['A source inventory, data definitions and quality assessment','Agreed pipelines, transformations or reporting prototypes','Validation rules, documentation and operational ownership'], 'Owners for your source systems, sample structures and the decisions your reporting should support.', 'discovery-brief','software-project'),
 'cloud-and-devops': ('Releases are difficult, environments drift or platform operations need a clearer plan.', ['A platform assessment and target environment design','Agreed infrastructure and delivery pipeline changes','Deployment, monitoring and recovery runbooks'], 'Your environment inventory, delivery process and approved access to the relevant systems.', 'handover-checklist','software-project'),
 'dedicated-teams': ('You know where delivery needs to go, but need the right engineering capacity.', ['A capability brief and proposed team composition','An onboarding plan with responsibilities and shared working hours','An agreed review rhythm and knowledge-transfer approach'], 'Your stack, priority work, required skills and the people who will lead day-to-day delivery.', 'delivery-roadmap','dedicated-team'),
 'enterprise-solutions': ('Teams re-enter information and business systems do not work well together.', ['A workflow and integration map with system ownership','Agreed configuration, automation or integration increments','Reconciliation checks, training material and support documentation'], 'Process owners, system documentation and the workflow you want to improve.', 'architecture-decision','software-project'),
 'quality-and-security': ('You need a clearer view of delivery risks and evidence to support a release decision.', ['An agreed review scope and quality criteria','Findings with evidence, priority and recommended remediation','A retest record and remaining-risk summary'], 'The system scope, relevant environments and explicit permission for any testing activities.', 'quality-review','consultation'),
 'managed-services': ('A live application needs dependable ownership, maintenance and improvement.', ['An application and support-readiness review','A service runbook with agreed responsibilities and escalation','A maintenance backlog and reporting approach'], 'An application inventory, operating documentation and your required service coverage.', 'handover-checklist','consultation'),
}

def close():
 return '<section class="next-step"><div class="wrap"><p class="eyebrow">LET’S MAKE THE NEXT STEP CLEAR</p><div><h2>A challenge worth solving.<br><em>A team to solve it with.</em></h2>'+a('start-a-project','Discuss your project','button')+'</div><p>Share what you know. We’ll explore the scope, the right people and a practical way forward.</p></div></section>'

def apply_consultancy(pages,services,sectors,articles,header,footer,components):
 def page(slug,title,desc,body): pages[slug]={'title':title,'description':desc,'html':body}
 def model_links():
  return ''.join(f'<article class="engagement-choice"><p class="eyebrow">{m[1]}</p><h3>{m[2]}</h3><p>{m[3]}</p>'+a('engagement-models#'+m[0],'Explore this approach')+'</article>' for m in MODELS)
 def samples_list(limit=None):
  return ''.join(f'<a class="sample-row" href="{url("sample-deliverables/"+s[0])}"><span class="sample-type">EDITABLE TEMPLATE</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div><span aria-hidden="true">↗</span></a>' for s in SAMPLES[:limit])
 home=f'''<section class="consultancy-hero"><div class="wrap consultancy-hero-grid"><div class="consultancy-hero-copy"><p class="eyebrow">UK-LED CONSULTING · AFRICAN ENGINEERING</p><h1>Build better<br>software.<br><em>Put AI to work.</em></h1><p class="lead">From the first decision to production, SIT brings strategy, software, data and engineering teams together around your business.</p><div class="actions">{a('start-a-project','Discuss your project','button')}{a('engagement-models','Find your way forward')}</div><p class="hero-small">UK client leadership. Developers in Liberia and across Africa.<br>One connected delivery team.</p></div><figure class="consultancy-art"><img src="{asset('bridge-apple-gold.png')}" width="1536" height="1024" alt="Sculptural orange and yellow bridge representing connected delivery" fetchpriority="high"><figcaption><span>SIT / CONNECTED DELIVERY</span><strong>Good thinking.<br>Built into reality.</strong></figcaption></figure></div></section>
<section class="wrap engagement-intro section"><div class="section-heading"><div><p class="eyebrow">THREE WAYS TO MOVE FORWARD</p><h2>The right starting point<br>for the work ahead.</h2></div>{a('engagement-models','Compare ways to work')}</div><div class="engagement-choices">{model_links()}</div></section>
<section class="capabilities-band"><div class="wrap section"><div class="section-heading"><div><p class="eyebrow">EXPERTISE THAT WORKS TOGETHER</p><h2>From complex questions<br>to useful technology.</h2></div>{a('services','Explore all nine services')}</div><div class="capability-editorial">{''.join(f'<a href="{url("services/"+s[0])}"><h3>{s[1]}</h3><p>{s[2]}</p><span aria-hidden="true">↗</span></a>' for s in [services[0],services[1],services[2],services[3],services[4],services[5]])}</div>{a('technologies','Explore our technology toolkit')}</div></section>
<section class="wrap section sample-showcase"><div><p class="eyebrow">MAKE DELIVERY TANGIBLE</p><h2>See what good<br>delivery looks like.</h2><p class="lead">Explore the documents that make decisions, quality and ownership clear.</p><p>These original templates illustrate our proposed approach. They are examples you can adapt for your own planning.</p>{a('sample-deliverables','Browse all five templates','button secondary')}</div><div class="sample-list">{samples_list(3)}</div></section>
<section class="delivery-story"><div class="wrap section"><div class="section-heading"><div><p class="eyebrow">UK LEADERSHIP / AFRICAN INGENUITY</p><h2>Close to your business.<br>Connected to your team.</h2></div><p>UK coordination and engineering talent in Africa, including Liberia. Agree the responsibilities, shared working hours and review rhythm before delivery begins.</p></div><ol class="delivery-stages">{''.join(f'<li><span>0{i+1}</span><h3>{t}</h3><p>{c}</p></li>' for i,(t,c) in enumerate([('Understand','Frame the user problem, constraints and outcome.'),('Agree','Define scope, owners and acceptance criteria.'),('Build','Review working increments and resolve decisions.'),('Transfer','Release with documentation and clear ownership.')]))}</ol><div class="delivery-links">{a('how-we-work','Meet our delivery model')}{a('delivery-assurance','Review delivery assurance')}{a('capabilities','View company capabilities')}</div></div></section>
<section class="wrap section ai-start"><div><p class="eyebrow">AI WITH A CLEAR PURPOSE</p><h2>Start with a useful problem.<br><em>Find your next step.</em></h2><p>Our five-question planner helps you decide what needs attention before discovery, a pilot or controlled delivery.</p>{a('ai-readiness','Plan your AI project','button')}<p class="muted">No sign-up. Your answers stay in the page.</p></div><div class="ai-principles"><span class="ai-symbol" aria-hidden="true">AI +</span><h3>Human judgement.<br>Engineering discipline.</h3><p>Approved information. Visible evaluation. Engineers accountable for the result.</p>{a('services/ai-and-automation','Explore AI & automation')}</div></section>
<section class="sector-focus"><div class="wrap section"><div class="section-heading"><div><p class="eyebrow">BUILT AROUND YOUR CONTEXT</p><h2>Your sector shapes the solution.</h2></div>{a('industries','Explore all sectors')}</div><div class="sector-ribbon">{''.join(a('industries#'+str(i),sectors[i][0],'sector-ribbon-link') for i in range(4))}</div></div></section>
<section class="wrap section home-perspectives"><div><p class="eyebrow">SIT PERSPECTIVES</p><h2>Better questions.<br>Better beginnings.</h2></div><div>{''.join(f'<a href="{url("insights/"+r[0])}"><p class="eyebrow">{r[1]}</p><h3>{r[2]}</h3><p>{r[3]}</p><span aria-hidden="true">↗</span></a>' for r in articles)}</div></section>{close()}'''
 page('','Software, AI and engineering consultancy','UK-led consulting, software, AI, data and dedicated engineering teams in Africa. Explore delivery approaches and discuss your project.',home)
 # Detailed, genuinely comparable offers with no invented costs or availability.
 rows=[('Best suited to',3),('What you receive',4),('How responsibility works',5),('Commercial approach',6)]
 cards=''.join(f'<article id="{m[0]}" class="model-card"><p class="eyebrow">{m[1]}</p><h2>{m[2]}</h2><dl>'+''.join(f'<div><dt>{label}</dt><dd>{m[idx]}</dd></div>' for label,idx in rows)+f'</dl>{a("start-a-project?type="+m[7]+"&goal="+m[8],"Discuss this approach","button")}</article>' for m in MODELS)
 page('engagement-models','Ways to work together','Compare discovery and advisory, project delivery and dedicated engineering teams.',intro('WAYS TO WORK TOGETHER','Choose the model.<br><em>Shape the work together.</em>','Start with what you need to achieve. Scope, responsibilities, fees and availability are confirmed in a proposal.')+'<section class="wrap section compact"><div class="model-comparison">'+cards+'</div><p class="note muted">You can begin with discovery and move into delivery. A dedicated team can also work alongside your existing partners.</p></section><section class="wrap section"><div class="section-heading"><div><p class="eyebrow">START WITH YOUR AMBITION</p><h2>Still deciding where to begin?</h2></div></div>[sit_component name="ambition-explorer"]</section>'+close())
 # Real files and readable sample pages share the same authored source.
 assets=Path(__file__).resolve().parents[1]/'wordpress/themes/sit-technology/assets/samples'
 assets.mkdir(parents=True,exist_ok=True)
 page('sample-deliverables','Sample delivery documents','Read, print and download five editable SIT Consultancy delivery templates.',intro('THE WORK BEHIND THE WORK','Clear decisions.<br><em>Useful documentation.</em>','Five original templates for discovery, architecture, delivery, quality and handover. Read them here, print them or download an editable copy.')+'<section class="wrap section compact"><p class="sample-disclosure">Illustrative templates, not client case studies or evidence of completed engagements. Adapt scope and review requirements to your project.</p><div class="sample-library">'+samples_list()+'</div></section>'+close())
 for slug,title,desc,sections in SAMPLES:
  md=f'# {title}\n\nSIT Consultancy — editable sample\n\nIllustrative template, not a client deliverable. Adapt it to your project.\n\n'+''.join(f'## {t}\n\n{c}\n\n' for t,c in sections)
  (assets/(slug+'.md')).write_text(md)
  body=intro('SAMPLE DELIVERABLE',title,desc)+f'<article class="wrap sample-document"><div class="sample-disclosure">Editable example · No client data · Adapt to your project</div><div class="sample-actions"><a class="button" href="{asset("samples/"+slug+".md")}" download>Download template <span aria-hidden="true">↓</span></a><a href="#main" class="button secondary" data-print>Print / save PDF</a>{a("sample-deliverables","All templates")}</div>'+''.join(f'<section><h2>{t}</h2><p>{escape(c).replace(chr(10),"<br>")}</p></section>' for t,c in sections)+f'<div class="sample-actions">{a("start-a-project","Discuss your project","button")}</div></article>'
  page('sample-deliverables/'+slug,title,desc+' An editable SIT Consultancy sample.',body)
 # Service content is specific, with shared navigation and clear commercial boundaries.
 for s in services:
  slug,title,tagline,desc,caps,number=s
  problem,outputs,inputs,sample,kind=SERVICE_DETAIL[slug]
  query='start-a-project?service='+slug+'&type='+kind
  questions=[('What happens after I send a brief?','We review the challenge and clarify the scope, relevant skills and practical next step. An enquiry does not commit you to an engagement.'),('What determines the price and timeline?','Scope, dependencies, existing systems, access and the agreed delivery model. We confirm estimates and acceptance criteria in a proposal before work starts.'),('Can you work with our existing team?','Yes. We first agree responsibilities, access, shared working hours and how decisions will be made. Relevant skills and availability are confirmed for the proposed team.')]
  if slug=='ai-and-automation': questions.append(('How do you evaluate AI output?','Agree representative examples, expected behaviour, unacceptable outcomes and human review before a pilot. Assess quality and limitations against those examples before a release decision.'))
  if slug=='managed-services': questions.append(('Is around-the-clock support included?','Coverage, response targets and escalation are defined in the service agreement. No coverage or service-level target is implied by this page.'))
  page('services/'+slug,title,desc,intro('OUR EXPERTISE / '+title.upper(),title+'.<br><em>'+tagline+'</em>',desc)+f'<div class="wrap service-start">{a(query,"Discuss this service","button")}{a("engagement-models","Compare engagement models")}</div><nav class="service-section-nav wrap" aria-label="On this service page"><a href="#challenge">The challenge</a><a href="#deliverables">Deliverables</a><a href="#starting">Getting started</a><a href="#questions">Questions</a></nav><section class="wrap service-content"><div><section id="challenge"><p class="eyebrow">WHERE WE CAN HELP</p><h2>{problem}</h2><ul class="service-capabilities">'+''.join(f'<li>{c}</li>' for c in caps)+'</ul></section><section id="deliverables"><p class="eyebrow">WHAT YOU CAN EXPECT</p><h2>Useful outputs.<br>Agreed from the start.</h2><ol class="output-list">'+''.join(f'<li>{o}</li>' for o in outputs)+'</ol><p class="muted">These are proposed outputs. The final scope and acceptance criteria are agreed for your engagement.</p></section><section id="starting"><p class="eyebrow">A PRACTICAL FIRST STEP</p><h2>Bring the context.<br>We’ll shape the approach.</h2><p class="lead">'+inputs+'</p><p>Begin with a short brief. Together we can clarify the outcome, examine constraints and agree whether discovery, project delivery or a dedicated team fits the work.</p>'+a(query,'Build your brief','button')+'</section><section id="questions" class="service-faq"><p class="eyebrow">BEFORE WE BEGIN</p><h2>Your questions, answered.</h2>'+''.join(f'<details><summary>{q}</summary><p>{answer}</p></details>' for q,answer in questions)+'</section></div><aside class="service-aside"><p class="eyebrow">SEE A SAMPLE</p><h3>'+next(x[1] for x in SAMPLES if x[0]==sample)+'</h3><p>A practical example of the documentation behind good delivery.</p>'+a('sample-deliverables/'+sample,'Read the template')+'<hr><p class="eyebrow">HOW WE WORK</p><p>UK client leadership, connected engineering and agreed review points.</p>'+a('delivery-assurance','Explore delivery assurance')+'</aside></section>'+close())
 pages['about'] = build_about_page()
 company_pages, components['contact-locations'] = build_company_pages(services)
 pages.update(company_pages)
 pages['about']['html'] += '<div class="wrap company-about-links">'+a('team','Explore our proposed team roles')+a('contact#locations','Contact our regional locations')+'</div>'
 # All website-facing branding uses the approved wordmark; technical slugs stay stable.
 for p in pages.values():
  for key in ('title','description','html'): p[key]=p[key].replace('SIT Technology','SIT Consultancy').replace('SIT TECHNOLOGY','SIT CONSULTANCY')
 records=[{'title':p['title'],'description':p['description'],'url':url(slug),'category':('Expertise' if slug.startswith('services') else 'Templates' if slug.startswith('sample-deliverables') else 'Insight' if slug.startswith('insights') else 'Company')} for slug,p in pages.items() if slug not in ('privacy','accessibility')]
 search_data=json.dumps(records,ensure_ascii=False).replace('<','\\u003c')
 header=re.sub(r'(<script type="application/json" id="sit-search-data">).*?(</script>)',lambda m:m[1]+search_data+m[2],header,flags=re.S)
 header=header.replace('SIT TECHNOLOGY','SIT CONSULTANCY').replace('Search SIT Technology','Search SIT Consultancy').replace('Let’s talk','Discuss a project').replace(a('careers','Careers','utility-link'),a('engagement-models','Ways to work','utility-link'))
 header=header.replace(a('about','About','nav-link'), '<details class="company-menu"><summary>Company <span aria-hidden="true">⌄</span></summary><div class="company-menu-panel">'+a('about','About SIT')+a('team','Our team roles')+a('contact','Contact us')+a('careers','Careers')+'</div></details>')
 footer=footer.replace('SIT Technology','SIT Consultancy')
 footer=footer.replace('<h2>Get to know SIT</h2>', '<h2>Get to know SIT</h2>'+a('contact','Contact us','footer-link')+a('team','Our team roles','footer-link'))
 footer=footer.replace('<h2>Think ahead</h2>','<h2>Plan your next step</h2>'+a('engagement-models','Ways to work','footer-link')+a('sample-deliverables','Sample deliverables','footer-link'))
 pages['how-we-work']['html']=pages['how-we-work']['html'].replace('<section class="section wrap faq">','<div class="wrap service-start">'+a('engagement-models','Compare engagement models','button')+'</div><section class="section wrap faq">')
 pages['privacy']['html']=pages['privacy']['html'].replace('</main>','')+'<section class="wrap article-body"><h2>Optional project context and downloads</h2><p>The brief builder can include intended users, existing systems, integrations, desired outcomes and delivery requirements. These optional answers are submitted with your request on the configured WordPress site. Draft downloads are created in your browser when you choose to download; keep that file on a device you control. The form does not automatically save drafts in browser storage.</p></section>'
 pages['privacy']['html'] += '<section class="wrap article-body"><h2>Contact enquiries</h2><p>The Contact form collects your name, email, organisation or individual status, message, topic and preferred location to review and respond to your enquiry. It uses the same private request desk and retention arrangements described above. It does not enrol you in marketing, store a personal draft in your browser or accept file uploads. Office map links open Google Maps only when you choose to follow them.</p></section>'
 return pages,header,footer,components
