"""SIT's second design: client-led discovery, editorial hierarchy and useful tools."""
import json,html

def url(path):return '{{url:'+path+'}}'
def asset(name):return '{{asset:'+name+'}}'
def a(path,label,cls='text-link'):
 return f'<a class="{cls}" href="{url(path)}">{label}<span aria-hidden="true">↗</span></a>'
def intro(kicker,title,copy):
 return f'<section class="page-hero wrap"><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="lead">{copy}</p></section>'
def ending():
 return f'<section class="closing"><div class="wrap closing-inner"><p class="eyebrow">YOUR NEXT CHAPTER STARTS WITH A CONVERSATION</p><div><h2>Let’s build<br>something <em>that matters.</em></h2>{a("start-a-project","Tell us what’s next","button light")}</div><p>A clear challenge. An open conversation. A practical way forward.</p></div></section>'
def apply_redesign(pages,services,sectors,articles,header,footer):
 components={}
 def page(slug,title,desc,body):pages[slug]={'title':title,'description':desc,'html':body}
 # Navigation groups are deliberately short enough to scan without nested menus.
 groups=[('Plan & modernise',[0,4,3]),('Build & connect',[1,2,6]),('Scale & sustain',[5,7,8])]
 brand=f'<a class="brand" href="{url("")}" aria-label="SIT Technology home"><span class="brand-symbol" aria-hidden="true">sit<span>↗</span></span><span class="brand-name">SIT<br><b>TECHNOLOGY</b></span></a>'
 mega=''.join('<div><p class="eyebrow">'+name+'</p>'+''.join(a('services/'+services[i][0],services[i][1],'mega-link') for i in ids)+'</div>' for name,ids in groups)
 header=f'''<a class="skip-link" href="#main">Skip to content</a><div class="utility-bar"><div class="wrap"><span>UK leadership <i aria-hidden="true">/</i> African engineering</span><div>{a('capabilities','Company capabilities','utility-link')}{a('careers','Careers','utility-link')}</div></div></div><header class="site-header"><div class="wrap nav-shell">{brand}<button class="menu-toggle" aria-expanded="false" aria-controls="primary-nav">Menu <span aria-hidden="true">☰</span></button><nav id="primary-nav" class="primary-nav" aria-label="Main navigation"><div class="nav-expertise"><button class="expertise-toggle" aria-expanded="false" aria-controls="expertise-menu">Expertise <span aria-hidden="true">⌄</span></button><div class="mega-menu" id="expertise-menu" hidden><div class="mega-intro"><p class="eyebrow">GOOD THINKING. GREAT ENGINEERING.</p><h2>From possibility<br>to practical progress.</h2>{a('services','Explore all expertise')}{a('technologies','Our technology toolkit')}</div><div class="mega-groups">{mega}</div><div class="mega-foot"><span>Not sure where to start?</span>{a('ai-readiness','Try the AI project planner')}</div></div></div>{a('industries','Industries','nav-link')}{a('how-we-work','How we work','nav-link')}{a('insights','Insights','nav-link')}{a('about','About','nav-link')}<button class="search-open" aria-label="Search SIT Technology"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/></svg></button>{a('start-a-project','Let’s talk','button nav-cta')}</nav></div></header>'''
 # Home: a decisive editorial first viewport followed by practical client choices.
 page('', 'Ambition, engineered', 'UK-led technology consulting, software engineering, AI and dedicated teams connecting African talent with your next ambition.',f'''
<section class="flagship-hero"><div class="hero-image"><img src="{asset('bridge-apple-gold.png')}" alt="" width="1536" height="1024" fetchpriority="high"></div><div class="wrap flagship-content"><p class="eyebrow">TECHNOLOGY CONSULTING & ENGINEERING</p><h1>Ambition,<br><em>engineered.</em></h1><p>Build what’s next. Make AI useful.<br>Bring exceptional engineering into your team.</p><div class="actions">{a('start-a-project','Start a conversation','button')}{a('services','Explore our expertise','text-link inverse')}</div><div class="hero-caption"><span class="caption-rule"></span><span>UK client leadership.<br>African ingenuity. One connected team.</span></div></div><span class="hero-side-label" aria-hidden="true">POSSIBILITY → PROGRESS</span></section>
<section class="quick-paths wrap" aria-label="Find your starting point">{''.join(f'<a href="{url(path)}"><span class="index">0{i+1} / {label}</span><strong>{title}</strong><span class="quick-arrow" aria-hidden="true">↗</span></a>' for i,(label,title,path) in enumerate([('TRANSFORM','Move your business forward','services/technology-strategy'),('CREATE','Build your next digital product','services/software-engineering'),('SCALE','Grow your engineering capacity','services/dedicated-teams')]))}</section>
<section class="section wrap ambition-section"><div class="section-heading"><div><p class="eyebrow">START WITH THE POSSIBILITY</p><h2>Your next move.<br>Our shared mission.</h2></div><p>Big-picture thinking and hands-on engineering, shaped around what you want to achieve.</p></div>[sit_component name="ambition-explorer"]</section>
<section class="expertise-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">CONNECTED CAPABILITIES</p><h2>From the first question.<br>To the next breakthrough.</h2></div>{a('services','Find the right expertise','text-link inverse')}</div><div class="expertise-rows">{''.join(f'<a class="expertise-row" href="{url("services/"+s[0])}"><span class="index">{s[5]}</span><h3>{s[1]}</h3><p>{s[2]}</p><span aria-hidden="true">↗</span></a>' for s in [services[1],services[2],services[3],services[5]])}</div><div class="expertise-bottom"><span>Strategy. Software. AI. Data. Cloud. People.</span>{a('technologies','Explore our technology toolkit','text-link inverse')}</div></div></section>
<section class="section wrap connected-story"><div><p class="eyebrow">A DIFFERENT PERSPECTIVE</p><h2>Built across borders.<br>Aligned around <em>you.</em></h2><p class="lead">A UK-headquartered partner. Developers in Liberia and across Africa. Shared ambition from the first conversation to delivery.</p>{a('how-we-work','Meet our delivery model')}</div><div class="delivery-ledger"><article><span class="ledger-code">UK</span><div><p class="eyebrow">CLOSE TO YOUR BUSINESS</p><h3>Leadership & partnership</h3><p>A clear point of contact, an understanding of your goals and a plan you can work with.</p></div></article><article><span class="ledger-code">AF</span><div><p class="eyebrow">CONNECTED TO YOUR AMBITION</p><h3>Engineering & ingenuity</h3><p>Relevant technical talent, collaborative delivery and a commitment to quality.</p></div></article><div class="ledger-foot"><span>ONE TEAM. SHARED STANDARDS.</span>{a('delivery-assurance','How we build confidence')}</div></div></section>
<section class="ai-feature wrap"><div class="ai-feature-copy"><p class="eyebrow">AI, WITH A CLEAR PURPOSE</p><h2>The best place<br>to start with AI?<br><em>A useful problem.</em></h2><p>Explore whether your idea is ready for discovery, a focused pilot or a controlled delivery plan.</p>{a('ai-readiness','Find your AI starting point','button')}<span class="tool-note">Five questions. Practical next steps. No sign-up.</span></div><div class="ai-editorial"><span class="eyebrow">THE SIT APPROACH TO AI</span><div><span class="giant-symbol" aria-hidden="true">{{ }}</span><h3>Human judgment.<br>Intelligently amplified.</h3></div><p>Clear use cases. Responsible data access.<br>Engineers accountable for the result.</p>{a('services/ai-and-automation','Explore AI & automation','text-link inverse')}</div></section>
<section class="section wrap"><div class="section-heading"><div><p class="eyebrow">YOUR WORLD, UNDERSTOOD</p><h2>Technology is universal.<br>Your context is unique.</h2></div>{a('industries','Explore our sector focus')}</div><div class="sector-ribbon">{''.join(a('industries#'+str(i),sectors[i][0],'sector-ribbon-link') for i in range(4))}</div></section>
<section class="insights-home"><div class="wrap section"><div class="section-heading"><div><p class="eyebrow">PERSPECTIVES FOR WHAT’S NEXT</p><h2>Ideas to move you forward.</h2></div>{a('insights','Explore our thinking')}</div><div class="editorial-grid">{''.join(f'<a class="editorial-card" href="{url("insights/"+r[0])}"><div class="editorial-cover cover-{i}"><span class="cover-kicker">SIT / PERSPECTIVES</span><span class="cover-title">{"Build fast.<br>Think deeply." if i==0 else "Better questions.<br>Better beginnings."}</span><span class="cover-arrow" aria-hidden="true">↗</span></div><p class="eyebrow">{r[1]} · SIT PERSPECTIVE</p><h3>{r[2]}</h3><p>{r[3]}</p></a>' for i,r in enumerate(articles))}</div></div></section>{ending()}''')
 ambitions=[
 ('modernise','Modernise your business','Create room for what’s next.','Connect fragmented systems, improve everyday workflows and turn technology decisions into a clear roadmap.',['Understand your current landscape','Prioritise the changes that matter','Plan a manageable path to delivery'],[0,4,6]),
 ('build','Build a digital product','Make a promising idea useful.','Shape, design and engineer a product around the people who will use it, with quality and ownership built in.',['Define the user problem and success criteria','Prototype and validate the right experience','Build, release and keep improving'],[1,7,2]),
 ('team','Extend your team','Bring the right skills closer.','Add engineering capacity with an agreed team, shared tools and a delivery rhythm that fits your organisation.',['Agree the capabilities and responsibilities','Connect engineers with your existing team','Create visibility and share knowledge'],[5,8,3])]
 components['ambition-explorer']='<div class="ambition-explorer" data-tabs><div class="ambition-tabs" role="tablist" aria-label="Your ambition">'+''.join(f'<button role="tab" id="ambition-tab-{i}" aria-controls="ambition-panel-{i}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}"><span class="index">0{i+1}</span>{r[1]}<span aria-hidden="true">↗</span></button>' for i,r in enumerate(ambitions))+'</div><div class="ambition-panels">'+''.join(f'<section role="tabpanel" id="ambition-panel-{i}" aria-labelledby="ambition-tab-{i}" '+('hidden' if i else '')+f'><p class="eyebrow">{r[1].upper()}</p><h3>{r[2]}</h3><p>{r[3]}</p><ul class="check-list">'+''.join(f'<li>{x}</li>' for x in r[4])+f'</ul><div class="related-chips">'+''.join(a('services/'+services[j][0],services[j][1],'related-chip') for j in r[5])+f'</div>{a("start-a-project?goal="+r[0],"Explore this together","text-link")}</section>' for i,r in enumerate(ambitions))+'</div></div>'
 # Finder: search combines with category selection, with a clear empty state.
 categories=['strategy','engineering','ai-data','ai-data','cloud','teams','engineering','engineering','cloud']
 category_labels=[('all','All expertise'),('strategy','Strategy'),('engineering','Engineering'),('ai-data','AI & data'),('cloud','Cloud & operations'),('teams','Teams')]
 components['service-finder']='''<div class="service-finder" data-service-finder><div class="finder-toolbar"><div><label for="service-search">Find a capability</label><input id="service-search" type="search" placeholder="Try AI, cloud or engineering" autocomplete="off"></div><p id="service-count" role="status">9 services to explore</p></div><div class="filter-chips" aria-label="Filter services">'''+''.join(f'<button type="button" data-filter="{v}" aria-pressed="{str(v=="all").lower()}">{label}</button>' for v,label in category_labels)+'''</div><div class="finder-grid">'''+''.join(f'<a class="finder-card" href="{url("services/"+s[0])}" data-category="{categories[i]}" data-search="{html.escape((s[1]+" "+s[3]+" "+" ".join(s[4])).lower(),quote=True)}"><span class="card-top"><span class="index">{s[5]}</span><span aria-hidden="true">↗</span></span><h2>{s[1]}</h2><p>{s[3]}</p><span class="finder-outcome">{s[2]}</span></a>' for i,s in enumerate(services))+'''</div><div class="finder-empty" hidden><h2>Let’s try a broader search.</h2><p>Try “software”, “data” or choose all expertise.</p><button type="button" class="button secondary" data-reset-finder>Clear filters</button></div></div>'''
 page('services','Our expertise','Find the right SIT Technology expertise by business need, service category or keyword.',intro('OUR EXPERTISE','Big-picture thinking.<br><em>Hands-on delivery.</em>','A connected set of capabilities. One practical purpose: helping your organisation move forward.')+'<section class="wrap section compact">[sit_component name="service-finder"]</section>'+f'<section class="wrap decision-banner"><div><p class="eyebrow">NEED HELP CHOOSING?</p><h2>Start with the challenge.</h2><p>We’ll help you work out the right skills, approach and first step.</p></div>{a("start-a-project","Talk it through","button")}</section>'+ending())
 # Sector explorer shows solution ideas, not unverified client results.
 sector_ideas=[['Customer and adviser portals','Workflow and reporting automation','Data quality and operational dashboards'],['Learning and course platforms','Student and educator experiences','Learning data and reporting'],['Service coordination tools','Secure information workflows','Operational reporting'],['Accessible citizen-facing services','Case coordination workflows','Service performance dashboards'],['Commerce experiences and integrations','Customer support automation','Stock and operational insight'],['Operations coordination platforms','Tracking and status visibility','Data integration and reporting'],['Resource and asset visibility','Sustainability reporting workflows','Data quality and dashboards'],['Client and project portals','Knowledge assistants','CRM and workflow integration']]
 components['industry-explorer']='<div class="industry-explorer" data-tabs><div class="industry-tabs" role="tablist" aria-label="Choose an industry" aria-orientation="vertical">'+''.join(f'<button role="tab" id="sector-tab-{i}" aria-controls="sector-panel-{i}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}">{s[0]}<span aria-hidden="true">↗</span></button>' for i,s in enumerate(sectors))+'</div><div class="industry-panels">'+''.join(f'<section role="tabpanel" id="sector-panel-{i}" aria-labelledby="sector-tab-{i}" '+('hidden' if i else '')+f'><span class="sector-number" aria-hidden="true">0{i+1}</span><p class="eyebrow">SECTOR FOCUS</p><h2>{s[0]}</h2><p>{s[1]}</p><h3>What we can explore together</h3><ul class="check-list">'+''.join('<li>'+x+'</li>' for x in sector_ideas[i])+f'</ul>{a("start-a-project","Discuss your sector challenge","button")}</section>' for i,s in enumerate(sectors))+'</div></div>'
 # Anchor IDs from the first release are retained and open the matching panel.
 page('industries','Industries','Explore technology possibilities in eight sectors, from education and finance to professional services.',intro('INDUSTRIES','Your context.<br><em>Our starting point.</em>','Useful technology begins with the people, processes and pressures that shape your world.')+'<section class="wrap section compact">'+''.join(f'<span class="sector-anchor" id="{i}" data-sector-anchor="{i}"></span>' for i in range(len(sectors)))+'[sit_component name="industry-explorer"]<p class="note muted">These are our sector priorities and solution ideas. Relevant experience, team capabilities and references are discussed during discovery.</p></section>'+ending())
 # AI planner: a transparent qualitative branching guide, no arbitrary score.
 questions=[('purpose','A useful problem','How clearly is the business problem defined?',[('0','We’re exploring possibilities'),('1','We have a use case to investigate'),('2','We have a use case and success criteria')]),('data','The right information','What is the state of the data or knowledge it needs?',[('0','We don’t know what is available'),('1','Some sources are identified'),('2','Sources, ownership and access are understood')]),('owner','People and ownership','Who will own the outcome?',[('0','An owner has not been agreed'),('1','We have a sponsor to involve'),('2','A sponsor and delivery owner are agreed')]),('controls','Trust and oversight','How far have you considered risk and human review?',[('0','We haven’t explored this yet'),('1','We know the main questions'),('2','Review responsibilities and boundaries are defined')]),('delivery','A path to use','How will the idea fit into daily work?',[('0','We’re still working this out'),('1','We can trial it with a small group'),('2','We have users, a trial plan and operating ownership')])]
 components['ai-planner']='<div class="planner-layout"><form id="ai-planner" class="planner-form"><div class="planner-heading"><p class="eyebrow">FIVE QUESTIONS. A CLEARER NEXT STEP.</p><h2>Where are you starting?</h2><p>Choose the answer closest to your current situation.</p></div>'+''.join(f'<div class="planner-question"><span class="index">0{i+1}</span><div><label for="ai-{key}">{question}</label><select id="ai-{key}" name="{key}" required><option value="">Choose an answer</option>'+''.join(f'<option value="{v}">{label}</option>' for v,label in options)+'</select></div></div>' for i,(key,title,question,options) in enumerate(questions))+'<button class="button" type="submit">Show my next steps <span aria-hidden="true">↗</span></button><p class="field-hint">Your answers stay in this page. Nothing is sent or saved.</p></form><aside class="planner-side"><p class="eyebrow">PURPOSE BEFORE PLATFORM</p><h2>Good AI starts<br>with good questions.</h2><p>This guide helps you frame a useful first conversation. It does not certify readiness or replace technical discovery.</p><div><span>01</span><p>Start with value</p></div><div><span>02</span><p>Make ownership clear</p></div><div><span>03</span><p>Plan for real-world use</p></div></aside><section id="ai-result" class="planner-result" hidden tabindex="-1" aria-live="polite"><p class="eyebrow">YOUR SUGGESTED STARTING POINT</p><h2 id="ai-result-title"></h2><p id="ai-result-description"></p><h3>What to do next</h3><ul id="ai-result-actions" class="check-list"></ul><div class="actions">'+a('start-a-project?service=ai-and-automation','Discuss an AI project','button')+'<button type="button" id="ai-reset" class="button secondary">Review my answers</button></div><p class="muted">Planning guidance based on your answers, using SIT’s transparent rules. A discovery conversation confirms scope, risks and feasibility.</p></section></div>'
 page('ai-readiness','AI project planner','Five practical questions to help you plan your first or next AI project. No sign-up or data collection.',intro('A USEFUL FIRST STEP','From AI curiosity<br>to <em>a clearer plan.</em>','A short guide to help you see what is ready, what needs attention and where to start.')+'<section class="wrap section compact">[sit_component name="ai-planner"]</section>'+ending())
 tech=[('Applications & platforms',['TypeScript / JavaScript','Python','Java','C# / .NET','PHP','Go'],'Web applications, APIs, integrations and platform engineering.'),('Web & mobile experiences',['React','Next.js','Vue','Angular','Flutter','React Native'],'Interfaces and mobile experiences shaped around your users.'),('Data & AI',['SQL','Python','R','Data pipelines','Machine learning','Retrieval & AI agents'],'Trusted information, practical analytics and useful AI workflows.'),('Cloud & delivery',['Microsoft Azure','AWS','Google Cloud','Docker','Kubernetes','CI/CD'],'Architecture, automation and an agreed path to reliable operation.')]
 page('technologies','Our technology toolkit','Explore the languages, frameworks and platforms that shape SIT Technology delivery.',intro('OUR TECHNOLOGY TOOLKIT','The right technology.<br><em>For the right reason.</em>','We select tools around the problem, your existing environment and the people who will maintain the result.')+'<section class="wrap section compact"><div class="toolkit-grid">'+''.join(f'<article><p class="eyebrow">0{i+1} / ENGINEERING TOOLKIT</p><h2>{title}</h2><p>{desc}</p><div class="technology-tags">'+''.join('<span>'+t+'</span>' for t in tags)+'</div></article>' for i,(title,tags,desc) in enumerate(tech))+'</div><p class="note muted">The toolkit describes technologies considered for our services. Relevant engineer experience, platform choices and availability are confirmed for each engagement. Platform names do not imply a certified partnership.</p></section>'+ending())
 assurance=[('A clear definition of success','Before delivery, agree the business outcome, users, scope, acceptance criteria and who makes decisions.'),('An accountable team','Define delivery leadership, responsibilities, communication cadence, shared working hours and escalation routes.'),('Quality built into the work','Agree appropriate review, automated testing, accessibility checks, security practices and release gates.'),('Responsible use of AI','Agree approved tools, permitted data, human oversight and verification of generated code or outputs.'),('Clarity on data and ownership','Document access, confidentiality, intellectual property, data locations and any cross-border requirements in the engagement.'),('A practical handover','Plan documentation, knowledge transfer, operational ownership, support and the next improvement backlog.')]
 page('delivery-assurance','Delivery assurance','The questions and working practices SIT Technology uses to build confidence before and during delivery.',intro('HOW WE BUILD CONFIDENCE','Trust comes from<br><em>how the work gets done.</em>','Clear responsibilities, visible progress and agreed quality standards. These are the foundations we bring into the delivery conversation.')+'<section class="wrap section compact"><div class="assurance-grid">'+''.join(f'<article><span class="index">0{i+1}</span><h2>{title}</h2><p>{text}</p></article>' for i,(title,text) in enumerate(assurance))+'</div><div class="assurance-note"><h3>Evidence belongs in the conversation.</h3><p>Relevant experience, references, security requirements and contractual commitments should be reviewed for your specific project. This page describes our proposed working approach and makes no certification claim.</p></div></section>'+ending())
 page('capabilities','Company capabilities','A concise, printable overview of SIT Technology’s services, delivery model and engagement options.',intro('SIT TECHNOLOGY / CAPABILITY OVERVIEW','Ambition,<br><em>engineered.</em>','UK-led technology consulting and engineering, connecting African talent with your next challenge.')+'<section class="wrap capability-brief"><div class="brief-tools"><button class="button secondary" type="button" data-print>Print / save as PDF <span aria-hidden="true">↗</span></button><p class="muted">A concise overview to share with your team.</p></div><div class="brief-grid"><section><p class="eyebrow">WHO WE ARE</p><h2>A connected delivery partner.</h2><p>SIT Technology is headquartered in the UK, with developers in Africa including Liberia. We bring together consulting, engineering and a collaborative way of working.</p><h3>Our focus</h3><p>Modernise technology, create digital products and extend engineering capacity.</p></section><section><p class="eyebrow">WHAT WE DO</p><h2>Connected capabilities.</h2><ul>'+''.join('<li>'+s[1]+'</li>' for s in services)+'</ul></section><section><p class="eyebrow">HOW WE WORK</p><h2>A model that fits the work.</h2><ul><li>Discovery and advisory</li><li>Project delivery</li><li>Dedicated engineering teams</li></ul><p>Scope, team, commercial terms, data handling and acceptance criteria are agreed before delivery.</p></section><section><p class="eyebrow">START THE CONVERSATION</p><h2>Bring us your challenge.</h2><p>Share what you want to achieve, your current situation and any practical constraints.</p>'+a('start-a-project','Discuss a project','button')+'</section></div></section>'+ending())
 # Put engagement choices and assurance within easy reach on the delivery page.
 pages['how-we-work']['html']=pages['how-we-work']['html'].replace('<section class="section wrap faq">',f'<section class="wrap decision-banner"><div><p class="eyebrow">CONFIDENCE BY DESIGN</p><h2>Know what to expect.</h2><p>Explore the responsibilities and quality practices we agree before delivery.</p></div>{a("delivery-assurance","Explore delivery assurance","button secondary")}</section><section class="section wrap faq">')
 # New related routes on all service detail pages.
 for s in services:
  slug='services/'+s[0]
  pages[slug]['html']=pages[slug]['html'].replace('<section class="cta wrap">',f'<section class="wrap service-next"><h2>The right way to work together.</h2><div>{a("how-we-work","Compare engagement approaches")}{a("delivery-assurance","How we build confidence")}{a("technologies","Explore our toolkit")}</div></section><section class="cta wrap">')
 # Shared site search: a real local index and accessible native dialog.
 records=[{'title':p['title'],'description':p['description'],'url':url(slug),'category':('Expertise' if slug.startswith('services') else 'Insight' if slug.startswith('insights') else 'Company')} for slug,p in pages.items() if slug not in ('privacy','accessibility')]
 search_data=json.dumps(records,ensure_ascii=False).replace('<','\\u003c')
 header+=f'''<dialog id="site-search" class="search-dialog" aria-labelledby="search-title"><div class="search-dialog-head"><p class="eyebrow">SIT TECHNOLOGY</p><button type="button" class="search-close" aria-label="Close search">Close <span aria-hidden="true">×</span></button></div><h2 id="search-title">What can we help you find?</h2><label for="site-search-input">Search services, ideas and information</label><input id="site-search-input" type="search" placeholder="Try AI, teams or cloud" autocomplete="off"><div class="search-suggestions"><span>Popular:</span><button type="button" data-search-term="AI">AI</button><button type="button" data-search-term="engineering">Engineering</button><button type="button" data-search-term="delivery">Delivery</button></div><p id="search-status" role="status"></p><div id="search-results"></div></dialog><script type="application/json" id="sit-search-data">{search_data}</script>'''
 footer=f'''<footer class="site-footer"><div class="wrap"><div class="footer-top"><div>{brand}<p>Independent thinking.<br>Connected delivery.</p><span class="footer-origin">UNITED KINGDOM / AFRICA</span></div><div><h2>Expertise</h2>{''.join(a(path,label,'footer-link') for path,label in [('services','All services'),('technologies','Technology toolkit'),('industries','Industry focus'),('ai-readiness','AI project planner')])}</div><div><h2>Get to know SIT</h2>{''.join(a(path,label,'footer-link') for path,label in [('about','About us'),('how-we-work','How we work'),('delivery-assurance','Delivery assurance'),('careers','Careers')])}</div><div><h2>Think ahead</h2>{''.join(a(path,label,'footer-link') for path,label in [('insights','Insights'),('capabilities','Company capabilities'),('start-a-project','Start a conversation')])}<p>UK leadership.<br>African engineering.</p></div></div><div class="footer-bottom"><p>© {{{{year}}}} SIT Technology. All rights reserved.</p><div>{a('privacy','Privacy','footer-legal')}{a('accessibility','Accessibility','footer-legal')}</div><span>AMBITION, ENGINEERED.</span></div></div></footer>'''
 return pages,header,footer,components
